<?php

/**
 * @file
 * Contains metasonic_common.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function metasonic_common_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the metasonic_common module.
    case 'help.page.metasonic_common':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('customize') . '</p>';
      return $output;

    default:
  }
}

/**
 * Implements hook_theme().
 */
function metasonic_common_theme() {
  return [
    'metasonic_common' => [
      'template' => 'metasonic_common',
      'render element' => 'children',
    ],
  ];
}

/**
 * Implements hook_form_alter().
 */
function metasonic_common_form_alter(&$form, &$form_state, $form_id) {
  if (in_array($form_id, array('search_block_form'))) {
    $form['keys']['#attributes']['placeholder'] = t('Search...');
  }
}
